# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan D. Hall
url: https://jhall.github.io
## To build the website locally, comment out the previous line and run
## in terminal: 'bundle ex jekyll serve'. The website will be hosted at
## 'localhost:4000'.

# repository: jhall/jhall.github.io
github: [metadata]
email: jonathan.hall@ua.edu
description: >- # this means to ignore newlines in the text below
  Jonathan Hall's personal website.
twitter_username: jonathanhall2
github_username: jhall
minimal_mistakes_skin: "default" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jonathan D. Hall"
  avatar : "/assets/images/jonathan-d-hall.jpg"
  bio    : 
    Associate Professor of Real Estate and Economics at the University of Alabama. 
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jonathan.hall@ua.edu"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jonathanhall2"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/grantmcdermott"
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.ca/citations?user=EiX4608AAAAJ"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-3835-9097"
      
footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/jonathanhall2"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/grantmcdermott"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Social
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#twitter-cards-and-facebook-open-graph
og_image: /assets/images/default-thumb.png

# Analytics
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-6CSHZ04VTX"
    anonymize_ip: false # default

# Comments
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#disqus
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "grantmcdermott-blog"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /blog/tag-archive/

exclude: ['*.Rmd']